# @package _global_

# Self-play sampling: 15x11 open maze, asymmetric cheese
# Usage: alpharat-sample configs/sample/15x11_open_asymmetric.yaml

defaults:
  - /game: 15x11_open_asymmetric
  - /mcts: 5x5_tuned
  - _self_

group: 15x11_open_asymmetric

sampling:
  num_games: 50000
  workers: 4

checkpoint: null
