# Quick test config - 5 games
mcts:
  variant: decoupled_puct
  simulations: 50
  gamma: 1.0
  c_puct: 1.5

game:
  width: 7
  height: 7
  max_turns: 50
  cheese_count: 5

sampling:
  num_games: 5
  workers: 2

output_dir: batches/
checkpoint: null
